Nw/tcp3way&tcp4way
JulSaMo/CS-start pull request #36
Opened 2022-08-31 05:55 UTC by SeonJeon

## 🟣 공부한 내용
TCP 3way handshake와 4way handshake에 대해서 공부하였습니다.

## 🟣 공부하면서 생긴 의문점
OSI를 먼저 배우고 들어가면 더 좋았을거 같아서 OSI가 궁금합니다.

## 🟣 기타

2022-09-02 10:49 UTC, Rookie0031 commented on Computer Science/Network/tcp3&4way(전송제어프로그램).md
> +## TCP 3way Handshaking 역할 (Connection Establish)
악수라고 칭한게 웃기네요 ㅋㅋㅋㅋ

2022-09-02 10:54 UTC, Rookie0031 requested changes
## 고생하셨습니다!!!

와우 이번 내용은 저한텐 너무 어려웠는데요? ㅋㅋㅋㅋㅋㅋ 대충 요약해보자면...
#### 컴터끼리 정보를 주고 받기 위해서는 사전 작업이 필요한데 그 과정 중 하나가 TCP 3 handShake이다.
#### handShake는 몇 작업에 걸쳐 이루어지는지에 따라 3way 4way로 나뉜다
#### handShake 작업 동안 여러 종류의 패킷을 주고 받으며 그를 통해 각각의 컴퓨터 상태가 바뀐다.

근데 솔직히 뭔소린지 하나도 모르겠어서 모르거나 헷갈리는 용어들을 한번 나열하고 공부해볼까합니다

1. 포트
2. 플래그
3. 비트
4. 패킷
5. SYN 패킷
6. 라우팅
7. 세션

2022-09-03 05:44 UTC, GODNOEL approved these changes
## 깔끔한 정리 감사합니다!
제가 조사한 OSI 7계층에서 4계층 전송 계층에 TCP라는 개념이 나왔는데
해당 프로토콜이 TCP N-way Handshake 라는 과정을 거쳐서 시작되고 끝나는 거군요!
제가 이해를 위해 찾아본 사이트들도 첨부합니다.
다른분들이 이해하실때 도움 되셨으면 좋겠습니다!

``` 
💡 TCP (전송 제어 프로토콜)
- 두 개의 호스트를 연결하고 데이터 스트림을 교환하게 해주는 중요한 네트워크 프로토콜
- TCP는 데이터와 패킷이 보내진 순서대로 전달하는 것을 보장
- OSI 7계층에서 4계층 전송 계층(Transport Layer)에 속함
``` 
port와 TCP 프로토콜
https://m.blog.naver.com/ljh0326s/220888531881

TCP N-way Handshake 간단한 정리 영상
https://youtu.be/gPsSLwaFhYo

2022-09-03 06:16 UTC, GODNOEL commented on Computer Science/Network/tcp3&4way(전송제어프로그램).md
> +  - ESTABLISHED: 포트 연결 상태
이 포트 정보는 TCP 헤더에 담겨있는 정보인가요?

2022-09-04 09:40 UTC, deslog approved these changes
고생하셨습니다!!! TCP 하나가 막 이것저것 많아서 헷갈리기 시작하네요 ㅠㅠ 화이팅

포트 상태를 왜 알아야하는지 궁금해서 찾아봤습니다.
[NETSTAT란?](https://solog4something.tistory.com/9)
[포트 상태 메세지](https://nhj12311.tistory.com/532)

그리고 TCP 헤더에 어떤 정보를 담는지도 함께 보면 좋을 것같아서 링크 달아드려요!
[TCP헤더에는 무슨 정보가 담겨져있을까?](https://evan-moon.github.io/2019/11/10/header-of-tcp/)

2022-09-05 03:47 UTC, SeonJeon commented
> 고생하셨습니다!!! TCP 하나가 막 이것저것 많아서 헷갈리기 시작하네요 ㅠㅠ 화이팅
> 
> 포트 상태를 왜 알아야하는지 궁금해서 찾아봤습니다. [NETSTAT란?](https://solog4something.tistory.com/9) [포트 상태 메세지](https://nhj12311.tistory.com/532)
> 
> 그리고 TCP 헤더에 어떤 정보를 담는지도 함께 보면 좋을 것같아서 링크 달아드려요! [TCP헤더에는 무슨 정보가 담겨져있을까?](https://evan-moon.github.io/2019/11/10/header-of-tcp/)

오 헤더에 관한 내용이 너무 양이 많아서 생략한 감이 없잖아 있는데 보내주신 링크 내용이 굉장히 쉽게 잘 정리되어 있네요 감사합니다!

2022-09-05 03:51 UTC, SeonJeon commented on Computer Science/Network/tcp3&4way(전송제어프로그램).md
> +  - ESTABLISHED: 포트 연결 상태
말씀을 듣고 좀 찾아봤는데 어떤 상태에 정보가 제공되는지 저도 잘 모르겠네요...
근데 통신시 제공되는 헤더에 포함되는 내용은 아닌거 같고 그냥 통신의 과정을 가시화하기 위해 정해둔 상태이지 않을까 싶습니다..!
스터디 전에 더 찾아볼게요~!

2022-09-15 08:32 UTC, merged